# Generated by Django 4.2.5 on 2023-12-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pressure in hPa"
                    ),
                ),
                (
                    "pressure_error",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Error of pressure in hPa"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Observation time"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Time of tip event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Range",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "traveltime",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="2-way traveltime in microseconds",
                    ),
                ),
                (
                    "traveltime_error",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Error of 2-way traveltime in microseconds",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Observation time"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Temperature in degrees Celsius",
                    ),
                ),
                (
                    "temperature_error",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Error of Temperature in degrees Celsius",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Observation time"
                    ),
                ),
            ],
        ),
    ]
