# Generated by Django 4.2.5 on 2023-12-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rain",
            name="validflag",
            field=models.IntegerField(
                default=1,
                verbose_name="Validity of tip event (set to zero to insert a discontinuity)",
            ),
        ),
    ]
