# Generated by Django 4.2.5 on 2023-12-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TankConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deadzone",
                    models.FloatField(verbose_name="Height of the deadzone [m]"),
                ),
                (
                    "normalzone",
                    models.FloatField(
                        verbose_name="height of the top of the normal zone (above it will overflow)[m]"
                    ),
                ),
                (
                    "sounderheight",
                    models.FloatField(
                        verbose_name="Height of the range sensor above the bottom of the tank [m]"
                    ),
                ),
                (
                    "soundergpiopin",
                    models.IntegerField(
                        verbose_name="Raspberry gpio-pin number of the ultrasounder ranger"
                    ),
                ),
                (
                    "relay1name",
                    models.CharField(
                        max_length=30,
                        verbose_name="Descriptive Name for the first Relay attached RELAY1",
                    ),
                ),
                (
                    "relay1gpiopin",
                    models.IntegerField(
                        verbose_name="Raspberry gpio-pin number for controlling the first relay RELAY1"
                    ),
                ),
                (
                    "relay2name",
                    models.CharField(
                        max_length=30,
                        verbose_name="Descriptive Name for the second Relay attached RELAY2",
                    ),
                ),
                (
                    "relay2gpiopin",
                    models.IntegerField(
                        verbose_name="Raspberry gpio-pin number for controlling the second relay RELAY2"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.FloatField(
                        verbose_name="Height from the bottom of the tank in [m]"
                    ),
                ),
                (
                    "area",
                    models.FloatField(
                        verbose_name="Horizontal squared area at the indicated height, in [m2]"
                    ),
                ),
                (
                    "volume",
                    models.FloatField(verbose_name="Accumulated volume in [m3]"),
                ),
                (
                    "tankconfig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.tankconfig",
                    ),
                ),
            ],
        ),
    ]
