# Generated by Django 4.2.5 on 2023-12-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MQTTConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(max_length=50, verbose_name="MQTT broker")),
                (
                    "port",
                    models.IntegerField(
                        default=8883,
                        verbose_name="MQTT port used (8883 enables ssl, 1883 disables ssl)",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="wetcave",
                        max_length=30,
                        verbose_name="Root topic to subscribe to",
                    ),
                ),
                (
                    "qos",
                    models.IntegerField(
                        default=1, verbose_name="QOS level of subscribing messages"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="tankconfig",
            name="sounderheight",
            field=models.FloatField(
                default=1.0,
                verbose_name="Height of the range sensor above the bottom of the tank [m]",
            ),
        ),
    ]
