# Generated by Django 4.2.5 on 2023-12-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_mqttconfig_alter_tankconfig_sounderheight"),
    ]

    operations = [
        migrations.AddField(
            model_name="mqttconfig",
            name="clientid",
            field=models.CharField(
                default="wetcave_sub",
                max_length=30,
                verbose_name="Client id of the subscriber service",
            ),
        ),
        migrations.AddField(
            model_name="mqttconfig",
            name="password",
            field=models.CharField(
                default="mqttpw", max_length=30, verbose_name="MQTT Password"
            ),
        ),
        migrations.AddField(
            model_name="mqttconfig",
            name="user",
            field=models.CharField(
                default="mqqtuser", max_length=30, verbose_name="MQTT User name"
            ),
        ),
    ]
