# Generated by Django 4.2.5 on 2023-12-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_mqttconfig_clientid_mqttconfig_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mqttconfig",
            name="pubclientid",
            field=models.CharField(
                default="tankclient",
                max_length=30,
                verbose_name="Client id of the sensor data publisher",
            ),
        ),
        migrations.AlterField(
            model_name="mqttconfig",
            name="clientid",
            field=models.CharField(
                default="web",
                max_length=30,
                verbose_name="Client id of the subscriber service",
            ),
        ),
    ]
