# Generated by Django 4.2.5 on 2024-01-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_mqttconfig_usessl_alter_mqttconfig_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="tankconfig",
            name="mmtip",
            field=models.FloatField(
                default=0.34384,
                verbose_name="mm/m2 of rain per tipping event of the tipping bucket",
            ),
        ),
    ]
