# Generated by Django 4.2.5 on 2024-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_tankconfig_mmtip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tankconfig",
            name="relay1gpiopin",
        ),
        migrations.RemoveField(
            model_name="tankconfig",
            name="relay1name",
        ),
        migrations.RemoveField(
            model_name="tankconfig",
            name="relay2gpiopin",
        ),
        migrations.RemoveField(
            model_name="tankconfig",
            name="relay2name",
        ),
        migrations.RemoveField(
            model_name="tankconfig",
            name="soundergpiopin",
        ),
        migrations.AlterField(
            model_name="mqttconfig",
            name="broker",
            field=models.CharField(
                default="mqtt.server", max_length=50, verbose_name="MQTT broker"
            ),
        ),
    ]
